
project_id = "pnkpymzakolxgjegomqv"

[functions.razorpay]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.zerodha-auth]
verify_jwt = false

[functions.zerodha-data]
verify_jwt = true

[functions.fyers-auth]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-signup-email]
verify_jwt = false

[functions.analyze-trade-screenshot]
verify_jwt = true
