// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnkpymzakolxgjegomqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBua3B5bXpha29seGdqZWdvbXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODc4MTEsImV4cCI6MjA1OTg2MzgxMX0._J6lhZgn5LgAnxjQr7VlCHuAYsLnsBEGSO4HxB5Rec8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);